baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'NRCC'

#theme = 'hugo-theme-techdoc'
theme = 'PaperMod'
sectionPagesMenu = 'main'

[params]
defaultTheme = "light"
showtoc = true

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 1
endLevel = 6
ordered = false
